config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tasks#index'

  resources :tasks
  put '/done', to: 'tasks#done', as: :done_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true

  def pending?
    status == 'pending'
  end

  def done?
    status == 'done'
  end

  def done!
    self.update!(status: 'done')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: %i[show edit update destroy done]

  def index
    tasks = Task.all.order(:created_at)
    @mapped_tasks = TasksPresenter.new(tasks: tasks, status: status).map_tasks_data
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save!
    redirect_to root_path, notice: 'Tarefa criada'
  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def edit
    redirect_to root_path, alert: 'Tarefa já está feita' if @task.done?
  end

  def update
    @task.update!(task_params)
    redirect_to task_path(@task.id), notice: 'Tarefa atualizada'
  rescue ActiveRecord::RecordInvalid
    render :edit
  end

  def destroy
    @task.destroy
    redirect_to root_path, notice: 'Tarefa excluída'
  end

  def done
    return redirect_to root_path, alert: 'Tarefa já está feita' if @task.done?

    @task.done!
    redirect_to root_path, notice: 'Tarefa feita'
  rescue StandardError
    render :index, alert: 'Ocorreu um erro inesperado'
  end

  private

  def find_task
    @task = Task.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path, alert: 'Tarefa não encontrada'
  end

  def task_params
    params.require(:task).permit(:name)
  end

  def permitted_params
    params.permit(:status)
  end

  def status
    permitted_params[:status]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/97e1c048a9.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row mt-4">
  <div class="col">
    <%= link_to root_path, method: :get, class: "btn btn-danger" do %>
      <i class="fa-solid fa-left-long"></i>
      <span>Voltar</span>
    <% end %>
  </div>
</div>
<div class="row mt-3">
  <div class="col">
    <h2>
      <%= task_action %> <%= task.id.present? ? "##{task.id}" : '' %>
    </h2>
  </div>
</div>
<div class="row mt-2">
  <div class="col">
    <%= form_with model: task do |form| %>
      <div class="mb-3">
        <%= form.text_area :name, class:'form-control', placeholder:'Escreva o nome da tarefa' %>
        <% task.errors.full_messages_for(:name).each do |message| %>
          <span><%= message %></span>
        <% end %>
      </div>
      <div class="col-auto">
        <%= form.submit task_button, class:'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task, task_action: 'Editar tarefa', task_button: 'Editar' %>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col">
    <% flash.each do |type, message| %>
      <div class="alert <%= type == 'alert' ? 'alert-danger' : 'alert-success' %>" role="alert" id="taskAlert">
        <%= message %>
      </div>
    <% end %>
  </div>
</div>
<div class="row mt-3">
  <div class="col">
    <h1>Tarefas</h1>
  </div>
</div>
<div class="row mb-4">
  <div class="col">
    <%= link_to new_task_path, method: :get, class: "btn btn-success btn-index" do %>
      <span>Adicionar tarefa</span>
      <i class="fa-solid fa-circle-plus add-icon"></i>
    <% end %>
  </div>
  <div class="col">
    <%= link_to tasks_path(status: 'pending'), method: :get, class: "btn btn-danger btn-index" do %>
      <span>Pendentes</span>
      <span class="badge text-bg-light"><%= @mapped_tasks[:pending_tasks] %></span>
    <% end %>
  </div>
  <div class="col">
    <%= link_to tasks_path(status: 'done'), method: :get, class: "btn btn-primary btn-index" do %>
      <span>Feitas</span>
      <span class="badge text-bg-light"><%= @mapped_tasks[:done_tasks] %></span>
    <% end %>
  </div>
  <div class="col">
    <%= link_to tasks_path(status: nil), method: :get, class: "btn btn-dark btn-index" do %>
      <span>Total</span>
      <span class="badge text-bg-light"><%= @mapped_tasks[:total_tasks] %></span>
    <% end %>
  </div>
  <div class="col"></div>
  <div class="col"></div>
</div>
<div class="row m-0">
  <% @mapped_tasks[:tasks].each do |task| %>
    <div class="card card-margin <%= task.pending? ? 'text-bg-danger' : 'text-bg-primary' %>" style="max-width: 20rem;">
      <div class="card-header align-right">
        <%= link_to task_path(task), data: { method: :delete, confirm: 'Tem certeza que deseja apagar a tarefa?' }, class: "option-icon-margin" do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
        <div class="display-inline option-icon-margin <%= task.done? ? 'not-allowed-click' : '' %>">
          <%= link_to edit_task_path(task), class: "#{ 'blocked-click' if task.done? }" do %>
            <i class="fa-regular fa-pen-to-square"></i>
          <% end %>
        </div>
        <%= link_to task_path(task), class: "option-icon-margin" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      </div>
      <div class="card-body">
        <h5 class="card-title">#<%= task.id %></h5>
        <h6 class="card-text <%= task.done? ? 'text-line-through' : '' %>"><%= task.name%></h6>
      </div>
      <div class="card-footer align-center">
        <%= link_to done_task_path(id: task.id), method: :put, class: "#{ 'blocked-click' if task.done? }" do %>
          <i class="fa-solid <%= task.pending? ? 'fa-check' : '' %>"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<%= render 'form', task: @task, task_action: 'Nova tarefa', task_button: 'Adicionar' %>

app/views/tasks/show.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= type == 'alert' ? 'alert-danger' : 'alert-success' %>" role="alert" id="taskAlert">
    <%= message %>
  </div>
<% end %>
<div class="row mt-4">
  <div class="col">
    <%= link_to root_path, method: :get, class: "btn btn-danger" do %>
      <i class="fa-solid fa-left-long"></i>
      <span>Voltar</span>
    <% end %>
  </div>
</div>
<div class="row mt-4">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">#<%= @task.id %></h5>
        <h6 class="card-text <%= @task.done? ? 'text-line-through' : '' %>"><%= @task.name %></h6>
      </div>
      <div class="card-footer text-muted">
        <%= link_to task_path(@task), data: { method: :delete, confirm: 'Tem certeza que deseja apagar a tarefa?' }, class: "btn btn-danger btn-show" do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
        <%= link_to edit_task_path(@task), class: "btn btn-dark btn-show #{ 'disabled' if @task.done? }" do %>
          <i class="fa-regular fa-pen-to-square"></i>
        <% end %>
        <%= link_to done_task_path(id: @task.id),  method: :put, class: "btn btn-success btn-show #{ 'disabled' if @task.done? }" do %>
          <i class="fa-solid fa-check"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>